    FROM python:3.11-slim-bookworm
    	
    # Установка системных зависимостей для chromadb и sentence-transformers
    RUN apt-get update && apt-get install -y --no-install-recommends \
        build-essential \
        cmake \
        libopenblas-dev \
        liblapack-dev \
        libhdf5-dev \
        libgomp1 \
        && rm -rf /var/lib/apt/lists/* \
        && apt-get clean
	
	WORKDIR /app
    COPY requirements.txt .
    RUN pip install --no-cache-dir -r requirements.txt \
    && rm -rf /root/.cache/pip
	COPY app ./app
	CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
